name: build java

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - java/**

jobs:

  push:
    name: "random-stuff:java_${{ matrix.tag }}"
    runs-on: clearlinux-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 17
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_graalvm
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/lakema17/random-dockerfiles
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,${{ matrix.tag }}
            
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta_graalvm.outputs.tags }}
          labels: ${{ steps.meta_graalvm.outputs.labels }}
